### ISSUE TITLE
Un líder puede actualizar avances (retrasado, en proceso, completado) y KPIs.

### ISSUE THREAD

**Issue by robertocml** [JesusGuadiana/DasboardGol-2#11]
### Un líder puede actualizar avances (retrasado, en proceso, completado) y KPIs.

El estado de los avances dentro del sistema es catalogado con -1,0 y 1. Un líder siempre puede actualizar un determinado avance o un KPI.

### To-do:

- [ ] El usuario (líder), puede ingresar al sistema con sus credenciales, puede acceder a una determinada estrategia y puede cambiar el estatus de un avance con -1 para atrasado, 0 en proceso y 1 completado.

- [ ] El usuario (líder), puede editar el campo cuantas veces sea necesario.

- [ ] Se llevaron a cabo pruebas.

### Criterios de aceptación:
El sistema registra correctamente el avance y se le da un feedback al usuario del avance/ KPI que fue actualizado.
