### ISSUE TITLE
Calcular el avance por estrategia.

### ISSUE THREAD

**Issue by robertocml** [JesusGuadiana/DasboardGol-2#12]
### Calcular el avance por estrategia.

El sistema debe ser capaz de realizar los cálculos necesarios para generar avances por cada estrategia

### To-do

- [ ] El sistema es capaz de generar el avance adecuado por cada estrategia.
- [ ] El usuario no puede modificar el cálculo del avance.
- [ ] Se llevaron a cabo pruebas.

### Criterios de aceptación:
El cálculo se genera correctamente.
