### ISSUE TITLE
Como usuario puedo asignar una foto de equipo para una estrategia

### ISSUE THREAD

**Issue by JesusGuadiana** [JesusGuadiana/DasboardGol-2#27]
### Convsersacion
Agregar la opcion de agregar fotos de equipo por estrategia

### To-do
* [ ]  Implementar la la forma para subir la foto del equipo al sistema.
* [ ] Desplegar la foto del equipo en su estrategia correspondiente.
* [ ] Se llevaron acabo pruebas

### Criterios de aceptación
Se despliega la foto correspondiete a el equipo de cada estrategia
