### ISSUE TITLE
Calculo de % de avance GOL general

### ISSUE THREAD

**Issue by JesusGuadiana** [JesusGuadiana/DasboardGol-2#31]
### Convsersacion
Hacer el calculo del % avance general GOL de acuerdo a las formulas del excel.
### To-do
* [ ]  Descifrar el calculo del % de avance general GOL del excel.
* [ ]  Aplicar la formula para desplegar el % de avance.
* [ ] Se llevaron acabo pruebas

### Criterios de aceptación
El % de avance general GOL del sistema concuerda con el % que muestra el archivo excel.
