### ISSUE TITLE
KPI’S donde se carga cualquier valor y la herramienta te defina tu estado.

### ISSUE THREAD

**Issue by JesusGuadiana** [JesusGuadiana/DasboardGol-2#33]
### Convsersacion
Dependiendo del valor del KPI se asigna un estado.

NA | 1 |
-- | -- |
Meet | 2 | 
Partially Exceed | 3 |
Exceed | 4 | 

### To-do
* [ ]  Implementar forma para introducir el valor del KPI (1 - 4)
* [ ] Desplegar el resultado dependiendo del KPI que se envio.
* [ ] Se llevaron acabo pruebas

### Criterios de aceptación
Se despliega el estado del KPI dependiendo de el valor del KPI
