### ISSUE TITLE
Creacion del modelo de users.

### ISSUE THREAD

**Issue by JesusGuadiana** [JesusGuadiana/DasboardGol-2#6]
### Creación de modelo de users.
Implementar el modelo de users en codigo con los atributos acordados.

### Convsersacion
Los atributos de un usuario son (ID,Username,Password,blockCount, isBlocke, isActive,UserType)

### To-do
* [x]  El modelo esta implementado en el codigo.
* [x]  El modelo cuenta con los atributos acordados en la junta.
* [x] Se llevaron acabo pruebas

### Criterios de aceptación
El modelo contiene los atributos que se acordaron en la junta.
