### ISSUE TITLE
Creacion del modelo contacts.

### ISSUE THREAD

**Issue by JesusGuadiana** [JesusGuadiana/DasboardGol-2#7]
### Creación de modelo de contacts.
Implementar el modelo de contacts en codigo con los atributos acordados.

### Convsersacion
Los atributos de un contacts son (FirstName , LastName, MotherLastName, Fullname, Email, CompanyEmail, RegistrationDate, ActiveDate, DeleteDate, IsActive)

### To-do
* [x]  El modelo esta implementado en el codigo.
* [x]  El modelo cuenta con los atributos acordados en la junta.
* [ ] Se llevaron acabo pruebas

### Criterios de aceptación
El modelo contiene los atributos que se acordaron en la junta.
