### ISSUE TITLE
Creacion de login (back-end)

### ISSUE THREAD

**Issue by JesusGuadiana** [JesusGuadiana/DasboardGol-2#9]
### Creación de login (back-end).
Crear la logica para hacer login a el sistema.

### Convsersacion
La pagina de login tendra el logo de Go y los campos necesarios para entrar al sistema.

### To-do
* [x]  Administrador puede entrar a la plataforma por medio de login
* [x]  Lider puede entrar a la plataforma por medio del login.
* [x] Se llevaron acabo pruebas

### Criterios de aceptación
Los usuarios ( Administradores y Lideres) pueden ingresar a la plataforma.
